version: "3.8"
services:
  proxy:
    # ports:
    #   - "${DOMAIN_PORT?80}:80"
    #   - "8080"

    # note: this is the whole command, it does not merge arguments from multiple Compose files
    command:
      # Enable the Dashboard and API in insecure mode for local development
      - --api.insecure=true
      - --api.dashboard=true

      # The arguments below are from docker-compose.yml, with the following exclusions:
      # --providers.docker.swarmmode - docker swarm mode is not enabled

      # Entrypoint web is for HTTP
      - --entryPoints.web.address=:80
      # Enable Docker in Traefik, so that it reads labels from Docker services
      - --providers.docker
      # Add a constraint to only use services with the label for this stack
      # from the env var TRAEFIK_TAG
      - --providers.docker.constraints=Label(`traefik.constraint-label-stack`, `${TRAEFIK_TAG?Variable not set}`)
      # Do not expose all Docker services, only the ones explicitly exposed
      - --providers.docker.exposedbydefault=false
      # Enable the access log, with HTTP requests
      - --accesslog
      # Enable the Traefik log, for configurations and errors
      - --log
      # Enable the Dashboard and API
      - --api

    network_mode: service:tailscale
    networks:
      - "${TRAEFIK_PUBLIC_NETWORK?Variable not set}"
      - default

  db:
    ports:
      - "5432"

  queue:
    image: rabbitmq:3-management
    ports:
      - "5672"
      - "15672"
    volumes:
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf

  backend:
    volumes:
      - ./backend/grid:/app/grid
      - ./backend/alembic:/app/alembic
      - ../syft:/app/syft
      - ../../notebooks:/notebooks
      - ./data/package-cache:/root/.cache

    environment:
      - SERVER_HOST=http://${DOMAIN?Variable not set}
      - SYFT_USE_UVLOOP=0
      - DOMAIN_NAME=${DOMAIN_NAME?Variable not set}
      - NODE_TYPE=${NODE_TYPE?Variable not set}
      - PORT=8001
      - STACK_API_KEY=$STACK_API_KEY

    build:
      context: ../
      dockerfile: ./grid/backend/backend.dockerfile
      target: "backend"
    # command: bash -c "while true; do sleep 1; done" # Infinite loop to keep container live doing nothing
    command: /start-reload.sh
    labels:
      - traefik.http.services.${STACK_NAME?Variable not set}-backend.loadbalancer.server.port=8001
    network_mode: service:proxy

  backend_stream:
    depends_on:
      - db
      - backend
    volumes:
      - ./backend/grid:/app/grid
      - ./backend/alembic:/app/alembic
      - ../syft:/app/syft
      - ./data/package-cache:/root/.cache
    environment:
      - SERVER_HOST=http://${DOMAIN?Variable not set}
      - SYFT_USE_UVLOOP=0
      - DOMAIN_NAME=${DOMAIN_NAME?Variable not set}
      - NODE_TYPE=${NODE_TYPE?Variable not set}
      - STREAM_QUEUE=1
      - PORT=8011
      - STACK_API_KEY=$STACK_API_KEY

    build:
      context: ../
      dockerfile: ./grid/backend/backend.dockerfile
      target: "backend"
    # command: bash -c "while true; do sleep 1; done" # Infinite loop to keep container live doing nothing
    command: "waitforit -address=http://localhost:8001/api/v1/syft/metadata -status=200 -timeout=600 -- /start-reload.sh"
    labels:
      - traefik.http.services.${STACK_NAME?Variable not set}-backend-stream.loadbalancer.server.port=8011
    network_mode: service:proxy

  celeryworker:
    depends_on:
      - backend
    volumes:
      - ./backend/grid:/app/grid #- ./backend/app:/app
      - ./backend/alembic:/app/alembic
      - ../syft:/app/syft #- ../syft:/app/syft
      - ../../notebooks:/notebooks
      - ./data/package-cache:/root/.cache
    environment:
      - RUN=celery -A grid.worker worker -l info -Q main-queue --pool=gevent -c 500
      - SERVER_HOST=http://${DOMAIN?Variable not set}
      - SYFT_USE_UVLOOP=0
      - DOMAIN_NAME=${DOMAIN_NAME?Variable not set}
      - C_FORCE_ROOT=1
      - STACK_API_KEY=$STACK_API_KEY

    build:
      context: ../
      dockerfile: ./grid/backend/backend.dockerfile
      target: "backend"
    command: "waitforit -address=http://localhost:8001/api/v1/syft/metadata -status=200 -timeout=600 -- /worker-start.sh"
    network_mode: service:proxy

  frontend:
    profiles:
      - frontend
    build:
      context: ./frontend
      dockerfile: frontend.dockerfile
      args:
        FRONTEND_ENV: ${FRONTEND_ENV-development}
        TYPE: ${NODE_TYPE?Variable not set}
    volumes:
      - ./frontend/src:/app/src

  tailscale:
    hostname: ${DOMAIN_NAME?Variable not set}
    image: "${DOCKER_IMAGE_TAILSCALE?Variable not set}:${VERSION-latest}"
    build:
      context: ./vpn
      dockerfile: tailscale.dockerfile
    environment:
      - HOSTNAME=${DOMAIN_NAME?Variable not set}
      - STACK_API_KEY=$STACK_API_KEY

    volumes:
      - tailscale-data:/var/lib/tailscale
      - "/dev/net/tun:/dev/net/tun" # Required for tailscale to work
      # - ./grid/vpn:/tailscale
    cap_add: # Required for tailscale to work
      - net_admin
      - sys_module
    ports:
      - "${DOMAIN_PORT?80}:80"
      - "41641/udp"
      - "4000"
    depends_on:
      - "docker-host"

  headscale:
    profiles:
      - network
    hostname: headscale
    image: "${DOCKER_IMAGE_HEADSCALE?Variable not set}:${VERSION-latest}"
    build:
      context: ./vpn
      dockerfile: headscale.dockerfile
    volumes:
      - headscale-data:/headscale/data
      # - ./grid/vpn:/headscale
    environment:
      - NETWORK_NAME=omnet
      - STACK_API_KEY=$STACK_API_KEY
    ports:
      - "4000"
    labels:
      - traefik.enable=true
      - traefik.constraint-label-stack=${TRAEFIK_TAG?Variable not set}
      - traefik.http.routers.${STACK_NAME?Variable not set}-vpn-http.rule=PathPrefix(`/vpn`)
      - "traefik.http.routers.${STACK_NAME?Variable not set}-vpn-http.middlewares=${STACK_NAME?Variable not set}-vpn-http-stripprefix"
      - traefik.http.routers.${STACK_NAME?Variable not set}-vpn-http.entrypoint=web
      - "traefik.http.middlewares.${STACK_NAME?Variable not set}-vpn-http-stripprefix.stripprefix.prefixes=/vpn"
      - traefik.http.services.${STACK_NAME?Variable not set}-vpn.loadbalancer.server.port=8080

  docker-host:
    image: qoomon/docker-host
    cap_add:
      - net_admin
      - net_raw

networks:
  traefik-public:
    # For local dev, don't expect an external Traefik network
    external: false

volumes:
  tailscale-data:
  headscale-data:
