# Default values for pysyft.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# This will enable or disable postgresql and rabbitmq charts
tags:
  db: true
  queue: true

# Set of Global environment variables.
global:
  storageClass: ""

# Postgresql database
# Rererence link: https://artifacthub.io/packages/helm/bitnami/postgresql
db:
  postgresqlUsername: "postgres"
  postgresqlPassword: ""
  postgresqlDatabase: ""
  persistence:
    enabled: true
    existingClaim: ""
    storageClass: "standard"
    accessModes:
      - "ReadWriteOnce"
    size: 8Gi
    # annotations:
    #   helm.sh/resource-policy: "keep"
  resources:
    requests:
      memory: 256Mi
      cpu: 250m

# RabbitMQ message broker
# Reference link: https://artifacthub.io/packages/helm/bitnami/rabbitmq
queue:
  auth:
    username: "user"
    password: ""
    erlangCookie: "secretcookie"
  resources:
    limits:
      memory: 512Mi
      cpu: 500m
    requests:
      memory: 256Mi
      cpu: 250m
  serviceAccount:
    create: true
  rbac:
    create: true
  persistence:
    enabled: true
    existingClaim: ""
    storageClass: "standard"
    accessModes: "ReadWriteOnce"
    size: 8Gi
    # annotations:
    #   helm.sh/resource-policy: "keep"

frontend:
  persistence:
    enabled: false
    storageClass: "standard"
    accessModes: "ReadWriteMany"
  image:
    repository: openmined/grid-frontend
  
backend: 
  image:
    repository: openmined/grid-backend