stack:
  - ".github/workflows/stack-integration_tests.yml"
  - "**.py"
  - "**.cfg"
  - "**.yml"
  - "**.dockerfile"
  - "**.toml"
  - "**.txt"
  - "**.ini"
  - "**.sh"
  - "**.mako"

backend:
  - "../../.github/workflows/grid-backend_tests.yml"
  - "../syft/**.py"
  - "../syft/**.cfg"
  - "backend/**.py"
  - "backend/**.yml"
  - "backend/**.cfg"
  - "backend/**.dockerfile"
  - "backend/**.toml"
  - "backend/**.txt"
  - "backend/**.ini"
  - "backend/**.sh"
  - "backend/**.mako"

hagrid:
  - "../../.github/workflows/hagrid-pr_tests.yml"
  - "**.py"
  - "**.cfg"
  - "**.yml"
  - "**.dockerfile"
  - "**.toml"
  - "**.txt"
  - "**.ini"
  - "**.sh"

syft:
  - "../../.github/workflows/syft**.yml"
  - "**.py"
  - "**.proto"
  - "**.yml"
  - "**.cfg"
  - "**.dockerfile"
  - "**.toml"
  - "**.txt"
  - "**.ini"
  - "**.sh"
  - "**.mako"
