group: travis_latest
language: python
cache: pip
python:
  #- 2.7
  - 3.6
  #- nightly
  #- pypy
  #- pypy3
matrix:
  allow_failures:
    - python: nightly
    - python: pypy
    - python: pypy3
install:
  - sudo apt-get update
  - hash -r
  - pip3 install -r pip-dep/requirements.txt >build.log
  - pip3 install -r pip-dep/requirements_dev.txt >build.log
  - pip3 install -r pip-dep/requirements_udacity.txt >build.log
  - pip3 install scikit-learn >build.log
  - pip3 install flake8
  #- pip3 install flake8-docstrings
  - pip3 install flake8-comprehensions
  - pip3 install pep8-naming
  - python setup.py install >> build.log
before_script:
  # stop the build if there are Python syntax errors or undefined
  # names
  - flake8 --config=.flake8 .
  - black --check --verbose .
  # exit-zero treats all errors as warnings.
  # diverting from the standard 79 character line length in
  # accordance with this:
  # https://www.python.org/dev/peps/pep-0008/#a-foolish-consistency-is-the-hobgoblin-of-little-minds
  - flake8 . --count --exit-zero --statistics --select=E,F,W,C90
script:
  - coverage run -m pytest test
  - coverage report --fail-under 95 -m
  # ensuring coverage of tests stays at 100 until entire coverage can be 100
  - coverage report --fail-under 100 -m --include="test/*"
  # - bash scripts/execute_notebooks.sh
  # - if grep -q "Traceback (most recent call last):" nb_to_md.txt; then false; else true; fi
  - treon --threads 1 'examples/tutorials/Part 01 - The Basic Tools of Private Deep Learning.ipynb'
  - treon --threads 1 'examples/tutorials/Part 02 - Intro to Federated Learning.ipynb'
  - treon --threads 1 'examples/tutorials/Part 03 - Advanced Remote Execution Tools.ipynb'
  - treon --threads 1 'examples/tutorials/Part 04 - Federated Learning via Trusted Aggregator.ipynb'
  - treon --threads 1 'examples/tutorials/Part 05 - Welcome to the Sandbox.ipynb'
  - treon --threads 1 'examples/tutorials/Part 06 - Federated Learning on MNIST using a CNN.ipynb'
  - treon --threads 1 'examples/tutorials/Part 07 - Federated Learning with Federated Dataset.ipynb'
  - treon --threads 1 'examples/tutorials/Part 08 bis - Introduction to Protocols.ipynb'
  - treon --threads 1 'examples/tutorials/Part 08 - Introduction to Plans.ipynb'
  - treon --threads 1 'examples/tutorials/Part 09 - Intro to Encrypted Programs.ipynb'
  - treon --threads 1 'examples/tutorials/Part 10 - Federated Learning with Secure Aggregation.ipynb'
  - treon --threads 1 'examples/tutorials/Part 11 - Secure Deep Learning Classification.ipynb'
  - treon --threads 1 'examples/tutorials/Part 12 bis - Encrypted Training on MNIST.ipynb'
  - treon --threads 1 'examples/tutorials/Part 12 - Train an Encrypted Neural Network on Encrypted Data.ipynb'
  - treon --threads 1 'examples/tutorials/Part 13a - Secure Classification with Syft Keras and TFE - Public Training.ipynb'
  - treon --threads 1 'examples/tutorials/Part 13b - Secure Classification with Syft Keras and TFE - Secure Model Serving.ipynb'
  - treon --threads 1 'examples/tutorials/Part 13c - Secure Classification with Syft Keras and TFE - Private Prediction Client.ipynb'
notifications:
  on_success: change
  # `always` will be the setting below once code changes slow down
  on_failure: change
