{{- $serviceNodePort :=  .Values.service.nodePort -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "celeryworker.fullname" . }}
  labels:
    {{- include "celeryworker.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if $serviceNodePort }}
      nodePort: {{ $serviceNodePort }}
      {{- end }}
  selector:
    {{- include "celeryworker.selectorLabels" . | nindent 4 }}
