version: "3.9"
services:
  network:
    container_name: grid.network
    image: openmined/grid-network:latest
    build:
      context: ../
      dockerfile: docker/grid.Dockerfile
      args:
        - VERSION=latest
        - APP=network
        - APP_ENV=production
    environment:
      - DATABASE_URL=postgresql://postgres:dbpass@network-db:5432/network
      - APP_ENV=production
    ports:
      - "5001:5000"
    depends_on:
      - "network-db"
    networks: ["net"]
  network-db:
    container_name: grid.network.db
    image: postgres:12
    restart: always
    environment:
      POSTGRES_PASSWORD: dbpass
      POSTGRES_DB: network
    # volumes:
    #   - ./data/network/db/postgres:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks: ["net"]
  domain:
    container_name: grid.domain
    # stdin_open: true # docker run -i
    # tty: true # docker run -t
    # entrypoint: /bin/bash
    image: openmined/grid-domain:latest
    build:
      context: ../
      dockerfile: docker/grid.Dockerfile
      args:
        - VERSION=latest
        - APP=domain
        - APP_ENV=production
    environment:
      - DATABASE_URL=postgresql://postgres:dbpass@domain-db:5432/domain
      - APP_ENV=production
    ports:
      - "5002:5000"
    depends_on:
      - "domain-db"
    networks: ["net"]
  domain-db:
    container_name: grid.domain.db
    image: postgres:12
    restart: always
    environment:
      POSTGRES_PASSWORD: dbpass
      POSTGRES_DB: domain
    # volumes:
    #   #   - ./data/domain/db/postgres:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks: ["net"]

networks:
  net:
    name: local-grid
