---
om_user: om
om_group: om
om_homedir: "/home/{{ om_user }}"
syft_dir: "/home/om/PySyft"
github_repo: OpenMined/PySyft
repo_branch: "0.6.0"
docker_compose_plugin_dir: ".docker/cli-plugins"
node_name: node
node_type: domain
root_user: root
root_homedir: "/{{ root_user }}"
