---
- name: Apply system changes
  import_tasks: system.yml
  when: deploy_only is not defined

- name: Install docker
  import_tasks: docker.yml
  when: deploy_only is not defined

- name: Delete PySyft Repo
  shell: "rm -rf {{ syft_dir }} || true"
  become_user: "{{ om_user }}"
  when: vagrant is not defined

- name: Clone PySyft Repo
  git:
    repo: "https://github.com/{{ github_repo }}"
    dest: "{{ syft_dir }}"
    version: "{{ repo_branch }}"
  become_user: "{{ om_user }}"
  ignore_errors: yes
  when: vagrant is not defined

- name: PySyft Repo Update Cron Job
  ansible.builtin.cron:
    name: "Update PySyft Repo"
    job: "cd {{ syft_dir }} && git checkout {{ repo_branch }} --force && git pull && chown -R om:om ."
  become: yes
  when: vagrant is not defined
