version: "3"
services:
  ngrok-datascientist-agent:
    image: wernight/ngrok
    command: ngrok http agent:${DATASCIENTIST_HTTP_PORT} --log stdout
    networks:
      - indy_demo
  datascientist-agent:
    build:
      context: ../../
      dockerfile: dockerfiles/agents/Dockerfile.ngrok
    environment:
      - NGROK_NAME=ngrok-datascientist-agent
      - ADMIN_URL=http://agent:${DATASCIENTIST_ADMIN_PORT}
      - DATASCIENTIST_NAME=${DATASCIENTIST_NAME}
      - ADMIN_PORT=${DATASCIENTIST_ADMIN_PORT}
      - HTTP_PORT=${DATASCIENTIST_HTTP_PORT}
      - WEBHOOK_URL=${DATASCIENTIST_WEBHOOK_URL}
      - DATASCIENTIST_ENDPOINT=${DATASCIENTIST_DATASCIENTIST_ENDPOINT}
      - WALLET_SEED=${DATASCIENTIST_WALLET_SEED}
      - WALLET_NAME=${DATASCIENTIST_WALLET_NAME}
      - WALLET_TYPE=${WALLET_TYPE}
      - WALLET_KEY=${DATASCIENTIST_WALLET_KEY}
      - ACAPY_ADMIN_INSECURE_MODE=true
      - GENESIS_URL=${GENESIS_URL}
    ports:
      - ${DATASCIENTIST_HTTP_PORT}:${DATASCIENTIST_HTTP_PORT}
      - ${DATASCIENTIST_ADMIN_PORT}:${DATASCIENTIST_ADMIN_PORT}
    networks:
      - indy_demo
    volumes:
      - agent:/home/indy/.indy_client/wallet
  datascientist-notebook:
    build:
      context: ../../
      dockerfile: dockerfiles/controllers/Dockerfile.attachmentcontroller
      args:
        - jupyter_port=${JUPYTER_PORT}
    depends_on:
      - agent
    networks:
      - indy_demo
    volumes:
      - ./notebooks/datascientist:/workspace
    ports:
      - "8888:8888"
      - ${DATASCIENTIST_WEBHOOK_PORT}:${DATASCIENTIST_WEBHOOK_PORT}
  ngrok-dataowner-agent:
    image: wernight/ngrok
    command: ngrok http agent:${DATAOWNER_HTTP_PORT} --log stdout
    networks:
      - indy_demo
  dataowner-agent:
    build:
      context: ../../
      dockerfile: dockerfiles/agents/Dockerfile.ngrok
    environment:
      - NGROK_NAME=ngrok-dataowner-agent
      - ADMIN_URL=http://agent:${DATAOWNER_ADMIN_PORT}
      - DATAOWNER_NAME=${DATAOWNER_NAME}
      - ADMIN_PORT=${DATAOWNER_ADMIN_PORT}
      - HTTP_PORT=${DATAOWNER_HTTP_PORT}
      - WEBHOOK_URL=${DATAOWNER_WEBHOOK_URL}
      - DATAOWNER_ENDPOINT=${DATAOWNER_DATAOWNER_ENDPOINT}
      - WALLET_SEED=${DATAOWNER_WALLET_SEED}
      - WALLET_NAME=${DATAOWNER_WALLET_NAME}
      - WALLET_TYPE=${WALLET_TYPE}
      - WALLET_KEY=${DATAOWNER_WALLET_KEY}
      - ACAPY_ADMIN_INSECURE_MODE=true
      - GENESIS_URL=${GENESIS_URL}
    ports:
      - ${DATAOWNER_HTTP_PORT}:${DATAOWNER_HTTP_PORT}
      - ${DATAOWNER_ADMIN_PORT}:${DATAOWNER_ADMIN_PORT}
    networks:
      - indy_demo
    volumes:
      - agent:/home/indy/.indy_client/wallet
  dataowner-notebook:
    build:
      context: ../../
      dockerfile: dockerfiles/controllers/Dockerfile.attachmentcontroller
      args:
        - jupyter_port=${JUPYTER_PORT}
    depends_on:
      - agent
    networks:
      - indy_demo
    volumes:
      - ./notebooks/dataowner:/workspace
    ports:
      - "8888:8888"
      - ${DATAOWNER_WEBHOOK_PORT}:${DATAOWNER_WEBHOOK_PORT}
volumes:
  agent:
networks:
  indy_demo:
