version: "3"
services:
  ngrok-datascientist-agent:
    image: wernight/ngrok
    command: ngrok http datascientist-agent:${DATASCIENTIST_HTTP_PORT} --log stdout
    networks:
      - indy_demo
  datascientist-agent:
    build:
      context: .
      dockerfile: Dockerfile.agent
    environment:
      - NGROK_NAME=ngrok-datascientist-agent
      - ADMIN_URL=http://datascientist-agent:${DATASCIENTIST_ADMIN_PORT}
      - AGENT_NAME=${DATASCIENTIST_NAME}
      - ADMIN_PORT=${DATASCIENTIST_ADMIN_PORT}
      - HTTP_PORT=${DATASCIENTIST_HTTP_PORT}
      - WEBHOOK_URL=${DATASCIENTIST_WEBHOOK_URL}
      - AGENT_ENDPOINT=${DATASCIENTIST_ENDPOINT}
      - WALLET_SEED=${DATASCIENTIST_WALLET_SEED}
      - WALLET_NAME=${DATASCIENTIST_WALLET_NAME}
      - WALLET_TYPE=${WALLET_TYPE}
      - WALLET_KEY=${DATASCIENTIST_WALLET_KEY}
      - ACAPY_ADMIN_INSECURE_MODE=true
      - GENESIS_URL=${GENESIS_URL}
    ports:
      - ${DATASCIENTIST_HTTP_PORT}:${DATASCIENTIST_HTTP_PORT}
      - ${DATASCIENTIST_ADMIN_PORT}:${DATASCIENTIST_ADMIN_PORT}
    networks:
      - indy_demo
#    volumes:
#      - agent:/home/indy/.indy_client/wallet
  datascientist-notebook:
    build:
      context: .
      dockerfile: Dockerfile.basiccontroller
      args:
        - jupyter_port=${JUPYTER_PORT}
    depends_on:
      - datascientist-agent
    networks:
      - indy_demo
    volumes:
      - ./notebooks/datascientist:/workspace
    ports:
      - "8888:8888"
      - ${DATASCIENTIST_WEBHOOK_PORT}:${DATASCIENTIST_WEBHOOK_PORT}
  ngrok-dataowner-agent:
    image: wernight/ngrok
    command: ngrok http dataowner-agent:${DATAOWNER_HTTP_PORT} --log stdout
    networks:
      - indy_demo
  dataowner-agent:
    build:
      context: .
      dockerfile: Dockerfile.agent
    environment:
      - NGROK_NAME=ngrok-dataowner-agent
      - ADMIN_URL=http://dataowner-agent:${DATAOWNER_ADMIN_PORT}
      - AGENT_NAME=${DATAOWNER_NAME}
      - ADMIN_PORT=${DATAOWNER_ADMIN_PORT}
      - HTTP_PORT=${DATAOWNER_HTTP_PORT}
      - WEBHOOK_URL=${DATAOWNER_WEBHOOK_URL}
      - AGENT_ENDPOINT=${DATAOWNER_ENDPOINT}
      - WALLET_SEED=${DATAOWNER_WALLET_SEED}
      - WALLET_NAME=${DATAOWNER_WALLET_NAME}
      - WALLET_TYPE=${WALLET_TYPE}
      - WALLET_KEY=${DATAOWNER_WALLET_KEY}
      - ACAPY_ADMIN_INSECURE_MODE=true
      - GENESIS_URL=${GENESIS_URL}
    ports:
      - ${DATAOWNER_HTTP_PORT}:${DATAOWNER_HTTP_PORT}
      - ${DATAOWNER_ADMIN_PORT}:${DATAOWNER_ADMIN_PORT}
    networks:
      - indy_demo
#    volumes:
#      - agent:/home/indy/.indy_client/wallet
  dataowner-notebook:
    build:
      context: .
      dockerfile: Dockerfile.basiccontroller
      args:
        - jupyter_port=${JUPYTER_PORT}
    depends_on:
      - dataowner-agent
    networks:
      - indy_demo
    volumes:
      - ./notebooks/dataowner:/workspace
    ports:
      - "8889:8888"
      - ${DATAOWNER_WEBHOOK_PORT}:${DATAOWNER_WEBHOOK_PORT}
#volumes:
#  agent:
networks:
  indy_demo:
