[package]
name    = "syft-core"
version = "0.1.0"
authors = ["Madhava Jay <me@madhavajay.com>", "Ben Szymkow <simcof@gmail.com>"]
edition = "2018"

[lib]
name = "syft_core"

[dependencies]
tokio       = { version = "1.6.0", features = ["macros", "rt-multi-thread"] }
tonic       = { version = "0.4.3", features = ["transport"] }
prost       = "0.7.0"
lazy_static = "1.4.0"
uuid        = { version = "0.8.2", features = ["v4"] }
url         = "2.2.2"
prost-types = "0.7.0"
bytes = "1.0.1"
numpy = "0.13.1"

[build-dependencies]
tonic-build = "0.4.2"
prost-build = "0.7.0"
walkdir = "2.3.2"
