apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "frontend.fullname" . }}-config
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
spec:
  VERSION: {{ default "latest" .Values.env.VERSION }}
  VERSION_HASH: {{ default "unknown" .Values.env.VERSION_HASH }}
  selector:
    {{- include "frontend.selectorLabels" . | nindent 4 }}
