{{- if .Values.persistence.enabled }}
{{- if not .Values.persistence.existingClaim -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  {{- if .Values.persistence.annotations }}
  annotations:
{{ toYaml .Values.persistence.annotations | indent 4 }}
  {{- end }}
  name: {{ include "frontend.fullname" .}}-pvc
spec:
  accessModes:
  {{- range .Values.persistence.accessModes }}
    - {{ . | quote }}
  {{- end }}
  {{ include "pysyft.storage.class" (dict "persistence" .Values.persistence "global" .Values.global) }}
  resources:
    requests:
      storage: "{{ .Values.persistence.size }}"
{{- end -}}
{{- end }}