[package]
name    = "syft"
version = "0.5.0"
authors = ["Madhava Jay <me@madhavajay.com>"]
edition = "2018"

[lib]
name       = "libsyft"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.13.2", features = ["extension-module"] }
